output_format: json
project_name: FactCheckers
settings:
  concurrent_requests: 4
  concurrent_requests_per_domain: 2
  download_delay: 1
spiders:
  - politifact
  - desmog
  - carbon_brief
  - snopes
